# All the "secret" configuration for the backend — database connection,
# Supabase keys, admin login, etc. None of these values are hard-coded here;
# they're read from environment variables (or a local .env file in dev) so
# real credentials never get committed to the repo. On Railway, these are
# set in the project's "Variables" tab.

from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # Reads matching values from a `.env` file if one exists (local dev only —
    # Railway injects real environment variables instead, no file needed).
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Postgres connection string for the Supabase database.
    database_url: str

    # Supabase project URL + service-role key, used to upload/delete files
    # in the "media" storage bucket (product photos, hero videos, etc).
    supabase_url: str
    supabase_service_role_key: str
    supabase_media_bucket: str = "media"

    # Admin dashboard login. The password is never stored in plain text —
    # only its bcrypt hash (generated by scripts/hash_password.py) lives here.
    admin_username: str
    admin_password_hash: str
    # Secret key used to sign admin login sessions (JWT tokens).
    jwt_secret_key: str
    jwt_expire_minutes: int = 720  # 12 hours — how long an admin login lasts before re-login is required

    # Which websites are allowed to call this API from a browser (CORS).
    # Comma-separated list, e.g. "https://blushcloset.xyz,http://localhost:5500"
    allowed_origins: str = "*"

    @property
    def allowed_origins_list(self) -> list[str]:
        """Turns the comma-separated `allowed_origins` string into a real list."""
        if self.allowed_origins.strip() == "*":
            return ["*"]
        return [origin.strip() for origin in self.allowed_origins.split(",") if origin.strip()]


@lru_cache
def get_settings() -> Settings:
    """Loads settings once and reuses them everywhere (avoids re-reading env vars on every request)."""
    return Settings()
